<?php

class DatabaseSeeder extends Seeder {

	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		Eloquent::unguard();

		// $this->call('UserTableSeeder');
		//
		$this->call('LanguagesTableSeeder');
	}
}

/**
*
*/
class LanguagesTableSeeder extends Seeder
{

	public function run()
	{
		DB::table('languages')->delete();

		DB::table('languages')->insert(array(
			array('safe_name' => 'html5', 'name' => 'HTML5'),
			array('safe_name' => 'css', 'name' => 'CSS'),
			array('safe_name' => 'javascript', 'name' => 'JavaScript'),
			array('safe_name' => 'php', 'name' => 'PHP'),
			array('safe_name' => 'python', 'name' => 'Python'),
			array('safe_name' => 'ruby', 'name' => 'Ruby'),
			array('safe_name' => 'lua', 'name' => 'Lua'),
			array('safe_name' => 'bash', 'name' => 'Bash'),
			array('safe_name' => 'erlang', 'name' => 'Erlang'),
			array('safe_name' => 'go', 'name' => 'Go'),
			array('safe_name' => 'c', 'name' => 'C'),
			array('safe_name' => 'cpp', 'name' => 'C++'),
			array('safe_name' => 'diff', 'name' => 'Diff-output'),
			array('safe_name' => 'latex', 'name' => 'LaTeX'),
			array('safe_name' => 'sql', 'name' => 'SQL'),
			array('safe_name' => 'xml', 'name' => 'XML'),
			array('safe_name' => 'text', 'name' => 'Plain Text'),
			array('safe_name' => '4cs', 'name' => '4CS'),
			array('safe_name' => '6502acme', 'name' => 'MOS 6502'),
			array('safe_name' => '6502kickass', 'name' => 'MOS 6502 Kick Assembler'),
			array('safe_name' => '6502tasm', 'name' => 'MOS 6502 TASM/64TASS'),
			array('safe_name' => '68000devpac', 'name' => 'Motorola 68000 Devpac Assembler'),
			array('safe_name' => 'abap', 'name' => 'ABAP'),
			array('safe_name' => 'actionscript', 'name' => 'Actionscript'),
			array('safe_name' => 'actionscript3', 'name' => 'ActionScript3'),
			array('safe_name' => 'ada', 'name' => 'Ada'),
			array('safe_name' => 'algol68', 'name' => 'ALGOL 68'),
			array('safe_name' => 'apache', 'name' => 'Apache'),
			array('safe_name' => 'applescript', 'name' => 'AppleScript'),
			array('safe_name' => 'apt_sources', 'name' => 'Apt sources.list'),
			array('safe_name' => 'asm', 'name' => 'x86 Assembler'),
			array('safe_name' => 'asp', 'name' => 'ASP'),
			array('safe_name' => 'autoconf', 'name' => 'autoconf'),
			array('safe_name' => 'autohotkey', 'name' => 'Autohotkey'),
			array('safe_name' => 'autoit', 'name' => 'AutoIT'),
			array('safe_name' => 'avisynth', 'name' => 'AviSynth'),
			array('safe_name' => 'awk', 'name' => 'Awk'),
			array('safe_name' => 'bascomavr', 'name' => 'BASCOM AVR'),
			array('safe_name' => 'basic4gl', 'name' => 'Basic4GL'),
			array('safe_name' => 'bf', 'name' => 'Brainfuck'),
			array('safe_name' => 'bibtex', 'name' => 'BibTeX'),
			array('safe_name' => 'blitzbasic', 'name' => 'BlitzBasic'),
			array('safe_name' => 'bnf', 'name' => 'BNF (Backus-Naur form)'),
			array('safe_name' => 'boo', 'name' => 'Boo'),
			array('safe_name' => 'c_loadrunner', 'name' => 'C (for LoadRunner)'),
			array('safe_name' => 'c_mac', 'name' => 'C for Macs'),
			array('safe_name' => 'caddcl', 'name' => 'CAD DCL (Dialog Control Language)'),
			array('safe_name' => 'cadlisp', 'name' => 'AutoCAD/IntelliCAD Lisp'),
			array('safe_name' => 'cfdg', 'name' => 'CFDG'),
			array('safe_name' => 'cfm', 'name' => 'ColdFusion'),
			array('safe_name' => 'chaiscript', 'name' => 'ChaiScript'),
			array('safe_name' => 'cil', 'name' => 'CIL (Common Intermediate Language)'),
			array('safe_name' => 'clojure', 'name' => 'Clojure'),
			array('safe_name' => 'cmake', 'name' => 'CMake'),
			array('safe_name' => 'cobol', 'name' => 'COBOL'),
			array('safe_name' => 'coffeescript', 'name' => 'CoffeeScript'),
			array('safe_name' => 'csharp', 'name' => 'C#'),
			array('safe_name' => 'cuesheet', 'name' => 'Cuesheet'),
			array('safe_name' => 'd', 'name' => 'D'),
			array('safe_name' => 'dcs', 'name' => 'DCS'),
			array('safe_name' => 'delphi', 'name' => 'Delphi (Object Pascal)'),
			array('safe_name' => 'div', 'name' => 'DIV'),
			array('safe_name' => 'dos', 'name' => 'DOS'),
			array('safe_name' => 'dot', 'name' => 'dot'),
			array('safe_name' => 'e', 'name' => 'E'),
			array('safe_name' => 'ecmascript', 'name' => 'ECMAScript'),
			array('safe_name' => 'eiffel', 'name' => 'Eiffel'),
			array('safe_name' => 'email', 'name' => 'Email (mbox/eml/RFC format)'),
			array('safe_name' => 'epc', 'name' => 'Enerscript'),
			array('safe_name' => 'euphoria', 'name' => 'Euphoria'),
			array('safe_name' => 'f1', 'name' => 'Formula One'),
			array('safe_name' => 'falcon', 'name' => 'Falcon'),
			array('safe_name' => 'fo', 'name' => 'fo'),
			array('safe_name' => 'fortran', 'name' => 'Fortran'),
			array('safe_name' => 'freebasic', 'name' => 'FreeBasic'),
			array('safe_name' => 'fsharp', 'name' => 'F#'),
			array('safe_name' => 'gambas', 'name' => 'GAMBAS'),
			array('safe_name' => 'gdb', 'name' => 'GDB'),
			array('safe_name' => 'genero', 'name' => 'Genero'),
			array('safe_name' => 'genie', 'name' => 'Genie'),
			array('safe_name' => 'gettext', 'name' => 'GNU Gettext .po/.pot'),
			array('safe_name' => 'glsl', 'name' => 'glSlang'),
			array('safe_name' => 'gml', 'name' => 'GML'),
			array('safe_name' => 'gnuplot', 'name' => 'Gnuplot script'),
			array('safe_name' => 'groovy', 'name' => 'Groovy'),
			array('safe_name' => 'gwbasic', 'name' => 'GwBasic'),
			array('safe_name' => 'haskell', 'name' => 'Haskell'),
			array('safe_name' => 'hicest', 'name' => 'HicEst'),
			array('safe_name' => 'hq9plus', 'name' => 'HQ9+'),
			array('safe_name' => 'html4strict', 'name' => 'HTML 4.01 strict'),
			array('safe_name' => 'icon', 'name' => 'Icon'),
			array('safe_name' => 'idl', 'name' => 'Unoidl'),
			array('safe_name' => 'ini', 'name' => 'INI'),
			array('safe_name' => 'inno', 'name' => 'Inno Script'),
			array('safe_name' => 'intercal', 'name' => 'INTERCAL'),
			array('safe_name' => 'io', 'name' => 'Io'),
			array('safe_name' => 'j', 'name' => 'J'),
			array('safe_name' => 'java', 'name' => 'Java'),
			array('safe_name' => 'java5', 'name' => 'Java 5'),
			array('safe_name' => 'jquery', 'name' => 'jQuery'),
			array('safe_name' => 'klonec', 'name' => 'KLone with C'),
			array('safe_name' => 'klonecpp', 'name' => 'KLone with C++'),
			array('safe_name' => 'lb', 'name' => 'Liberty BASIC'),
			array('safe_name' => 'lisp', 'name' => 'Generic Lisp'),
			array('safe_name' => 'llvm', 'name' => 'LLVM'),
			array('safe_name' => 'locobasic', 'name' => 'Locomotive Basic (Amstrad CPC series)'),
			array('safe_name' => 'logtalk', 'name' => 'Logtalk'),
			array('safe_name' => 'lolcode', 'name' => 'LOLcode'),
			array('safe_name' => 'lotusformulas', 'name' => '@Formula/@Command'),
			array('safe_name' => 'lotusscript', 'name' => 'LotusScript'),
			array('safe_name' => 'lscript', 'name' => 'Lightwave Script'),
			array('safe_name' => 'lsl2', 'name' => 'Linden Scripting'),
			array('safe_name' => 'm68k', 'name' => 'Motorola 68000 Assembler'),
			array('safe_name' => 'magiksf', 'name' => 'MagikSF'),
			array('safe_name' => 'make', 'name' => 'Make'),
			array('safe_name' => 'mapbasic', 'name' => 'MapBasic'),
			array('safe_name' => 'matlab', 'name' => 'Matlab M-file'),
			array('safe_name' => 'mirc', 'name' => 'mIRC Scripting'),
			array('safe_name' => 'mmix', 'name' => 'MMIX Assembler'),
			array('safe_name' => 'modula2', 'name' => 'Modula-2'),
			array('safe_name' => 'modula3', 'name' => 'Modula-3'),
			array('safe_name' => 'mpasm', 'name' => 'Microchip Assembler'),
			array('safe_name' => 'mxml', 'name' => 'MXML'),
			array('safe_name' => 'mysql', 'name' => 'MySQL'),
			array('safe_name' => 'newlisp', 'name' => 'newLISP'),
			array('safe_name' => 'nsis', 'name' => 'Nullsoft Scriptable Install System'),
			array('safe_name' => 'oberon2', 'name' => 'Oberon-2'),
			array('safe_name' => 'objc', 'name' => 'Objective-C'),
			array('safe_name' => 'objeck', 'name' => 'Objeck Programming Language'),
			array('safe_name' => 'ocaml', 'name' => 'OCaml (Objective Caml)'),
			array('safe_name' => 'oobas', 'name' => 'OpenOffice.org Basic'),
			array('safe_name' => 'oracle11', 'name' => 'Oracle 11i'),
			array('safe_name' => 'oracle8', 'name' => 'Oracle 8'),
			array('safe_name' => 'oxygene', 'name' => 'Delphi Prism (Oxygene)'),
			array('safe_name' => 'oz', 'name' => 'Oz'),
			array('safe_name' => 'pascal', 'name' => 'Pascal'),
			array('safe_name' => 'pcre', 'name' => 'PCRE'),
			array('safe_name' => 'per', 'name' => 'Per (forms)'),
			array('safe_name' => 'perl', 'name' => 'Perl'),
			array('safe_name' => 'perl6', 'name' => 'Perl 6'),
			array('safe_name' => 'pf', 'name' => 'OpenBSD packet filter'),
			array('safe_name' => 'pic16', 'name' => 'PIC16 Assembler'),
			array('safe_name' => 'pike', 'name' => 'Pike'),
			array('safe_name' => 'pixelbender', 'name' => 'Pixel Bender 1.0'),
			array('safe_name' => 'pli', 'name' => 'PL/I'),
			array('safe_name' => 'plsql', 'name' => 'Oracle PL/SQL'),
			array('safe_name' => 'postgresql', 'name' => 'PostgreSQL'),
			array('safe_name' => 'povray', 'name' => 'Povray'),
			array('safe_name' => 'powerbuilder', 'name' => 'PowerBuilder (PowerScript)'),
			array('safe_name' => 'powershell', 'name' => 'PowerShell'),
			array('safe_name' => 'proftpd', 'name' => 'ProFTPd'),
			array('safe_name' => 'progress', 'name' => 'Progress'),
			array('safe_name' => 'prolog', 'name' => 'Prolog'),
			array('safe_name' => 'properties', 'name' => 'Property'),
			array('safe_name' => 'providex', 'name' => 'ProvideX'),
			array('safe_name' => 'purebasic', 'name' => 'PureBasic'),
			array('safe_name' => 'q', 'name' => 'q/kdb+'),
			array('safe_name' => 'qbasic', 'name' => 'QBasic/QuickBASIC'),
			array('safe_name' => 'rails', 'name' => 'Ruby (with Ruby on Rails Framework)'),
			array('safe_name' => 'rebol', 'name' => 'Rebol'),
			array('safe_name' => 'reg', 'name' => 'Microsoft Registry Editor'),
			array('safe_name' => 'robots', 'name' => 'robots.txt'),
			array('safe_name' => 'rpmspec', 'name' => 'RPM Spec'),
			array('safe_name' => 'rsplus', 'name' => 'R'),
			array('safe_name' => 'sas', 'name' => 'SAS'),
			array('safe_name' => 'scala', 'name' => 'Scala'),
			array('safe_name' => 'scheme', 'name' => 'Scheme'),
			array('safe_name' => 'scilab', 'name' => 'SciLab'),
			array('safe_name' => 'sdlbasic', 'name' => 'sdlBasic'),
			array('safe_name' => 'smalltalk', 'name' => 'Smalltalk'),
			array('safe_name' => 'smarty', 'name' => 'Smarty template'),
			array('safe_name' => 'systemverilog', 'name' => 'SystemVerilog IEEE 1800-2009(draft8)'),
			array('safe_name' => 'tcl', 'name' => 'TCL/iTCL'),
			array('safe_name' => 'teraterm', 'name' => 'Tera Term Macro'),
			array('safe_name' => 'thinbasic', 'name' => 'thinBasic'),
			array('safe_name' => 'tsql', 'name' => 'T-SQL'),
			array('safe_name' => 'typoscript', 'name' => 'TypoScript'),
			array('safe_name' => 'unicon', 'name' => 'Unicon'),
			array('safe_name' => 'uscript', 'name' => 'UnrealScript'),
			array('safe_name' => 'vala', 'name' => 'Vala'),
			array('safe_name' => 'vb', 'name' => 'Visual Basic'),
			array('safe_name' => 'vbnet', 'name' => 'VB.NET'),
			array('safe_name' => 'verilog', 'name' => 'Verilog'),
			array('safe_name' => 'vhdl', 'name' => 'VHDL'),
			array('safe_name' => 'vim', 'name' => 'Vim scripting'),
			array('safe_name' => 'visualfoxpro', 'name' => 'Visual FoxPro'),
			array('safe_name' => 'visualprolog', 'name' => 'Visual Prolog'),
			array('safe_name' => 'whitespace', 'name' => 'Whitespace'),
			array('safe_name' => 'whois', 'name' => 'Whois response (RPSL format)'),
			array('safe_name' => 'winbatch', 'name' => 'WinBatch'),
			array('safe_name' => 'xbasic', 'name' => 'XBasic'),
			array('safe_name' => 'xorg_conf', 'name' => 'xorg.conf'),
			array('safe_name' => 'xpp', 'name' => 'Axapta/Dynamics Ax X++'),
			array('safe_name' => 'yaml', 'name' => 'YAML'),
			array('safe_name' => 'z80', 'name' => 'ZiLOG Z80 Assembler'),
			array('safe_name' => 'zxbasic', 'name' => 'ZXBasic')
		));
	}
}
