<?php

return array(
		array('safe_name' => 'html5'), array('name' => 'HTML5'),
		array('safe_name' => 'css'), array('name' => 'CSS'),
		array('safe_name' => 'javascript'), array('name' => 'JavaScript'),
		array('safe_name' => 'php'), array('name' => 'PHP'),
		array('safe_name' => 'python'), array('name' => 'Python'),
		array('safe_name' => 'ruby'), array('name' => 'Ruby'),
		array('safe_name' => 'lua'), array('name' => 'Lua'),
		array('safe_name' => 'bash'), array('name' => 'Bash'),
		array('safe_name' => 'erlang'), array('name' => 'Erlang'),
		array('safe_name' => 'go'), array('name' => 'Go'),
		array('safe_name' => 'c'), array('name' => 'C'),
		array('safe_name' => 'cpp'), array('name' => 'C++'),
		array('safe_name' => 'diff'), array('name' => 'Diff-output'),
		array('safe_name' => 'latex'), array('name' => 'LaTeX'),
		array('safe_name' => 'sql'), array('name' => 'SQL'),
		array('safe_name' => 'xml'), array('name' => 'XML'),
		array('safe_name' => 'text'), array('name' => 'Plain Text'),
		array('safe_name' => '4cs'), array('name' => '4CS'),
		array('safe_name' => '6502acme'), array('name' => 'MOS 6502'),
		array('safe_name' => '6502kickass'), array('name' => 'MOS 6502 Kick Assembler'),
		array('safe_name' => '6502tasm'), array('name' => 'MOS 6502 TASM/64TASS'),
		array('safe_name' => '68000devpac'), array('name' => 'Motorola 68000 Devpac Assembler'),
		array('safe_name' => 'abap'), array('name' => 'ABAP'),
		array('safe_name' => 'actionscript'), array('name' => 'Actionscript'),
		array('safe_name' => 'actionscript3'), array('name' => 'ActionScript3'),
		array('safe_name' => 'ada'), array('name' => 'Ada'),
		array('safe_name' => 'algol68'), array('name' => 'ALGOL 68'),
		array('safe_name' => 'apache'), array('name' => 'Apache'),
		array('safe_name' => 'applescript'), array('name' => 'AppleScript'),
		array('safe_name' => 'apt_sources'), array('name' => 'Apt sources.list'),
		array('safe_name' => 'asm'), array('name' => 'x86 Assembler'),
		array('safe_name' => 'asp'), array('name' => 'ASP'),
		array('safe_name' => 'autoconf'), array('name' => 'autoconf'),
		array('safe_name' => 'autohotkey'), array('name' => 'Autohotkey'),
		array('safe_name' => 'autoit'), array('name' => 'AutoIT'),
		array('safe_name' => 'avisynth'), array('name' => 'AviSynth'),
		array('safe_name' => 'awk'), array('name' => 'Awk'),
		array('safe_name' => 'bascomavr'), array('name' => 'BASCOM AVR'),
		array('safe_name' => 'basic4gl'), array('name' => 'Basic4GL'),
		array('safe_name' => 'bf'), array('name' => 'Brainfuck'),
		array('safe_name' => 'bibtex'), array('name' => 'BibTeX'),
		array('safe_name' => 'blitzbasic'), array('name' => 'BlitzBasic'),
		array('safe_name' => 'bnf'), array('name' => 'BNF (Backus-Naur form)'),
		array('safe_name' => 'boo'), array('name' => 'Boo'),
		array('safe_name' => 'c_loadrunner'), array('name' => 'C (for LoadRunner)'),
		array('safe_name' => 'c_mac'), array('name' => 'C for Macs'),
		array('safe_name' => 'caddcl'), array('name' => 'CAD DCL (Dialog Control Language)'),
		array('safe_name' => 'cadlisp'), array('name' => 'AutoCAD/IntelliCAD Lisp'),
		array('safe_name' => 'cfdg'), array('name' => 'CFDG'),
		array('safe_name' => 'cfm'), array('name' => 'ColdFusion'),
		array('safe_name' => 'chaiscript'), array('name' => 'ChaiScript'),
		array('safe_name' => 'cil'), array('name' => 'CIL (Common Intermediate Language)'),
		array('safe_name' => 'clojure'), array('name' => 'Clojure'),
		array('safe_name' => 'cmake'), array('name' => 'CMake'),
		array('safe_name' => 'cobol'), array('name' => 'COBOL'),
		array('safe_name' => 'coffeescript'), array('name' => 'CoffeeScript'),
		array('safe_name' => 'csharp'), array('name' => 'C#'),
		array('safe_name' => 'cuesheet'), array('name' => 'Cuesheet'),
		array('safe_name' => 'd'), array('name' => 'D'),
		array('safe_name' => 'dcs'), array('name' => 'DCS'),
		array('safe_name' => 'delphi'), array('name' => 'Delphi (Object Pascal)'),
		array('safe_name' => 'div'), array('name' => 'DIV'),
		array('safe_name' => 'dos'), array('name' => 'DOS'),
		array('safe_name' => 'dot'), array('name' => 'dot'),
		array('safe_name' => 'e'), array('name' => 'E'),
		array('safe_name' => 'ecmascript'), array('name' => 'ECMAScript'),
		array('safe_name' => 'eiffel'), array('name' => 'Eiffel'),
		array('safe_name' => 'email'), array('name' => 'Email (mbox/eml/RFC format)'),
		array('safe_name' => 'epc'), array('name' => 'Enerscript'),
		array('safe_name' => 'euphoria'), array('name' => 'Euphoria'),
		array('safe_name' => 'f1'), array('name' => 'Formula One'),
		array('safe_name' => 'falcon'), array('name' => 'Falcon'),
		array('safe_name' => 'fo'), array('name' => 'fo'),
		array('safe_name' => 'fortran'), array('name' => 'Fortran'),
		array('safe_name' => 'freebasic'), array('name' => 'FreeBasic'),
		array('safe_name' => 'fsharp'), array('name' => 'F#'),
		array('safe_name' => 'gambas'), array('name' => 'GAMBAS'),
		array('safe_name' => 'gdb'), array('name' => 'GDB'),
		array('safe_name' => 'genero'), array('name' => 'Genero'),
		array('safe_name' => 'genie'), array('name' => 'Genie'),
		array('safe_name' => 'gettext'), array('name' => 'GNU Gettext .po/.pot'),
		array('safe_name' => 'glsl'), array('name' => 'glSlang'),
		array('safe_name' => 'gml'), array('name' => 'GML'),
		array('safe_name' => 'gnuplot'), array('name' => 'Gnuplot script'),
		array('safe_name' => 'groovy'), array('name' => 'Groovy'),
		array('safe_name' => 'gwbasic'), array('name' => 'GwBasic'),
		array('safe_name' => 'haskell'), array('name' => 'Haskell'),
		array('safe_name' => 'hicest'), array('name' => 'HicEst'),
		array('safe_name' => 'hq9plus'), array('name' => 'HQ9+'),
		array('safe_name' => 'html4strict'), array('name' => 'HTML 4.01 strict'),
		array('safe_name' => 'icon'), array('name' => 'Icon'),
		array('safe_name' => 'idl'), array('name' => 'Unoidl'),
		array('safe_name' => 'ini'), array('name' => 'INI'),
		array('safe_name' => 'inno'), array('name' => 'Inno Script'),
		array('safe_name' => 'intercal'), array('name' => 'INTERCAL'),
		array('safe_name' => 'io'), array('name' => 'Io'),
		array('safe_name' => 'j'), array('name' => 'J'),
		array('safe_name' => 'java'), array('name' => 'Java'),
		array('safe_name' => 'java5'), array('name' => 'Java 5'),
		array('safe_name' => 'jquery'), array('name' => 'jQuery'),
		array('safe_name' => 'klonec'), array('name' => 'KLone with C'),
		array('safe_name' => 'klonecpp'), array('name' => 'KLone with C++'),
		array('safe_name' => 'lb'), array('name' => 'Liberty BASIC'),
		array('safe_name' => 'lisp'), array('name' => 'Generic Lisp'),
		array('safe_name' => 'llvm'), array('name' => 'LLVM'),
		array('safe_name' => 'locobasic'), array('name' => 'Locomotive Basic (Amstrad CPC series)'),
		array('safe_name' => 'logtalk'), array('name' => 'Logtalk'),
		array('safe_name' => 'lolcode'), array('name' => 'LOLcode'),
		array('safe_name' => 'lotusformulas'), array('name' => '@Formula/@Command'),
		array('safe_name' => 'lotusscript'), array('name' => 'LotusScript'),
		array('safe_name' => 'lscript'), array('name' => 'Lightwave Script'),
		array('safe_name' => 'lsl2'), array('name' => 'Linden Scripting'),
		array('safe_name' => 'm68k'), array('name' => 'Motorola 68000 Assembler'),
		array('safe_name' => 'magiksf'), array('name' => 'MagikSF'),
		array('safe_name' => 'make'), array('name' => 'Make'),
		array('safe_name' => 'mapbasic'), array('name' => 'MapBasic'),
		array('safe_name' => 'matlab'), array('name' => 'Matlab M-file'),
		array('safe_name' => 'mirc'), array('name' => 'mIRC Scripting'),
		array('safe_name' => 'mmix'), array('name' => 'MMIX Assembler'),
		array('safe_name' => 'modula2'), array('name' => 'Modula-2'),
		array('safe_name' => 'modula3'), array('name' => 'Modula-3'),
		array('safe_name' => 'mpasm'), array('name' => 'Microchip Assembler'),
		array('safe_name' => 'mxml'), array('name' => 'MXML'),
		array('safe_name' => 'mysql'), array('name' => 'MySQL'),
		array('safe_name' => 'newlisp'), array('name' => 'newLISP'),
		array('safe_name' => 'nsis'), array('name' => 'Nullsoft Scriptable Install System'),
		array('safe_name' => 'oberon2'), array('name' => 'Oberon-2'),
		array('safe_name' => 'objc'), array('name' => 'Objective-C'),
		array('safe_name' => 'objeck'), array('name' => 'Objeck Programming Language'),
		array('safe_name' => 'ocaml'), array('name' => 'OCaml (Objective Caml)'),
		array('safe_name' => 'oobas'), array('name' => 'OpenOffice.org Basic'),
		array('safe_name' => 'oracle11'), array('name' => 'Oracle 11i'),
		array('safe_name' => 'oracle8'), array('name' => 'Oracle 8'),
		array('safe_name' => 'oxygene'), array('name' => 'Delphi Prism (Oxygene)'),
		array('safe_name' => 'oz'), array('name' => 'Oz'),
		array('safe_name' => 'pascal'), array('name' => 'Pascal'),
		array('safe_name' => 'pcre'), array('name' => 'PCRE'),
		array('safe_name' => 'per'), array('name' => 'Per (forms)'),
		array('safe_name' => 'perl'), array('name' => 'Perl'),
		array('safe_name' => 'perl6'), array('name' => 'Perl 6'),
		array('safe_name' => 'pf'), array('name' => 'OpenBSD packet filter'),
		array('safe_name' => 'pic16'), array('name' => 'PIC16 Assembler'),
		array('safe_name' => 'pike'), array('name' => 'Pike'),
		array('safe_name' => 'pixelbender'), array('name' => 'Pixel Bender 1.0'),
		array('safe_name' => 'pli'), array('name' => 'PL/I'),
		array('safe_name' => 'plsql'), array('name' => 'Oracle PL/SQL'),
		array('safe_name' => 'postgresql'), array('name' => 'PostgreSQL'),
		array('safe_name' => 'povray'), array('name' => 'Povray'),
		array('safe_name' => 'powerbuilder'), array('name' => 'PowerBuilder (PowerScript)'),
		array('safe_name' => 'powershell'), array('name' => 'PowerShell'),
		array('safe_name' => 'proftpd'), array('name' => 'ProFTPd'),
		array('safe_name' => 'progress'), array('name' => 'Progress'),
		array('safe_name' => 'prolog'), array('name' => 'Prolog'),
		array('safe_name' => 'properties'), array('name' => 'Property'),
		array('safe_name' => 'providex'), array('name' => 'ProvideX'),
		array('safe_name' => 'purebasic'), array('name' => 'PureBasic'),
		array('safe_name' => 'q'), array('name' => 'q/kdb+'),
		array('safe_name' => 'qbasic'), array('name' => 'QBasic/QuickBASIC'),
		array('safe_name' => 'rails'), array('name' => 'Ruby (with Ruby on Rails Framework)'),
		array('safe_name' => 'rebol'), array('name' => 'Rebol'),
		array('safe_name' => 'reg'), array('name' => 'Microsoft Registry Editor'),
		array('safe_name' => 'robots'), array('name' => 'robots.txt'),
		array('safe_name' => 'rpmspec'), array('name' => 'RPM Spec'),
		array('safe_name' => 'rsplus'), array('name' => 'R'),
		array('safe_name' => 'sas'), array('name' => 'SAS'),
		array('safe_name' => 'scala'), array('name' => 'Scala'),
		array('safe_name' => 'scheme'), array('name' => 'Scheme'),
		array('safe_name' => 'scilab'), array('name' => 'SciLab'),
		array('safe_name' => 'sdlbasic'), array('name' => 'sdlBasic'),
		array('safe_name' => 'smalltalk'), array('name' => 'Smalltalk'),
		array('safe_name' => 'smarty'), array('name' => 'Smarty template'),
		array('safe_name' => 'systemverilog'), array('name' => 'SystemVerilog IEEE 1800-2009(draft8)'),
		array('safe_name' => 'tcl'), array('name' => 'TCL/iTCL'),
		array('safe_name' => 'teraterm'), array('name' => 'Tera Term Macro'),
		array('safe_name' => 'thinbasic'), array('name' => 'thinBasic'),
		array('safe_name' => 'tsql'), array('name' => 'T-SQL'),
		array('safe_name' => 'typoscript'), array('name' => 'TypoScript'),
		array('safe_name' => 'unicon'), array('name' => 'Unicon'),
		array('safe_name' => 'uscript'), array('name' => 'UnrealScript'),
		array('safe_name' => 'vala'), array('name' => 'Vala'),
		array('safe_name' => 'vb'), array('name' => 'Visual Basic'),
		array('safe_name' => 'vbnet'), array('name' => 'VB.NET'),
		array('safe_name' => 'verilog'), array('name' => 'Verilog'),
		array('safe_name' => 'vhdl'), array('name' => 'VHDL'),
		array('safe_name' => 'vim'), array('name' => 'Vim scripting'),
		array('safe_name' => 'visualfoxpro'), array('name' => 'Visual FoxPro'),
		array('safe_name' => 'visualprolog'), array('name' => 'Visual Prolog'),
		array('safe_name' => 'whitespace'), array('name' => 'Whitespace'),
		array('safe_name' => 'whois'), array('name' => 'Whois response (RPSL format)'),
		array('safe_name' => 'winbatch'), array('name' => 'WinBatch'),
		array('safe_name' => 'xbasic'), array('name' => 'XBasic'),
		array('safe_name' => 'xorg_conf'), array('name' => 'xorg.conf'),
		array('safe_name' => 'xpp'), array('name' => 'Axapta/Dynamics Ax X++'),
		array('safe_name' => 'yaml'), array('name' => 'YAML'),
		array('safe_name' => 'z80'), array('name' => 'ZiLOG Z80 Assembler'),
		array('safe_name' => 'zxbasic'), array('name' => 'ZXBasic')
);
